### PR TITLE
Feature/reset password frontend

### PR DESCRIPTION
**Pull request by flierc-csp**

### CODE REVIEW

**Review by noko12312 — APPROVED** [review]

**Review by thebaker10 — DISMISSED** [review]

**Comment by thebaker10** [comment]
trying to forget the password results in the following error: 
`
{
    "statusCode": 405,
    "error": {
        "type": "NOT_ALLOWED",
        "description": "Method not allowed. Must be one of: OPTIONS"
    }
}
`

**Comment by flierc-csp** [comment]
> trying to forget the password results in the following error: `{ "statusCode": 405, "error": { "type": "NOT_ALLOWED", "description": "Method not allowed. Must be one of: OPTIONS" } }`

@thebaker10 
Are you getting this in Postman, or is this being returned by the ajax request?

**Comment by flierc-csp** [comment]
@thebaker10 
Actually, I found an open curly brace which I just fixed.
Do you still have an issue with it?

**Comment by noko12312** [comment]
@flierc-csp The forgot-password request is going through for me, but we will be unable to test anything else because we do not have the SMTP credentials in our environment variables.

**Pull request merged**
